# Generated by Django 4.2.5 on 2023-09-18 17:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subone', '0002_userresponse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserResponse',
            new_name='UserResponsePreSub',
        ),
    ]
